#Q1-What is a database? Differentiate between SQL and NoSQL databases.
print('Database- An organized collection of data and information or interrelated data collected at one place.\n')
      
print('''SQL databases are primarily called as Relational Databases (RDBMS),
whereas NoSQL database are primarily called as non-relational or distributed database.''')


#Q2-What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.
print('''\nDDL- Data Definition Language actually consists of the SQL commands that can be used to define the database schema. 
DDL is a set of SQL commands used to create, modify, and delete database structures but not data.''')

print('\nCREATE-This command is used to create the database or its objects (like table, index, function, views')
import mysql.connector
mydb=mysql.connector.connect(
     host="localhost",
     user="abc",
     password="password")
mycursor=mydb.cursor()
mycursor.execute("CREATE DATABASE if not exists DATA")
mycursor.execute("CREATE TABLE if not exists DATA.INFO(Name char(10), Id int(5), Age int(20))")
print('DROP- This command is used to delete objects from the database.')
mycursor.execute("DROP TABLE DATA.INFO")
print('TRUNCATE-This is used to remove all records from a table, including all spaces allocated for the records are removed.')
mycursor.execute("CREATE TABLE if not exists DATA.INFO(Name char(10), Id int(5), Age int(20))")
mycursor.execute("TRUNCATE TABLE  DATA.INFO")
print('ALTER-This is used to alter the structure of the database.')
mycursor.execute("ALTER TABLE DATA.INFO ADD(Course char(50))")

#Q3-What is DML? Explain INSERT, UPDATE, and DELETE with an example.
print('\nDML-The SQL commands that deals with the manipulation of data present in the database belong to DML or Data Manipulation Language.')
print('It is the component of the SQL statement that controls access to data and to the database.')

print('INSERT : It is used to insert data into a table.')
mycursor.execute("INSERT INTO DATA.INFO(`Name`, `Id`, `Age`) VALUES('AMAN',02,21),('AYUSH JHA',05,23),('ABHIJIT',12,19)")
mydb.commit()

print('UPDATE: It is used to update existing data within a table.')
mycursor.execute("UPDATE DATA.INFO SET Course='Data science' WHERE Id=05")
mydb.commit()
print('DELETE : It is used to delete records from a database table.')
mycursor.execute("DELETE FROM  DATA.INFO WHERE Course='Data science'")
mydb.commit()

#Q4-What is DQL? Explain SELECT with an example.
print('\nDQL statements are used for performing queries on the data within schema objects.')
print('The purpose of the DQL Command is to get some schema relation based on the query passed to it.')

print('SELECT: It is used to retrieve data from the database.')
mycursor.execute("SELECT * FROM DATA.INFO")
for i in mycursor.fetchall():
     print(i)


#Q5-Explain Primary Key and Foreign Key.
print('\nPrimary Key- primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values. It is either an existing table column or a column that is specifically generated by the database according to a defined sequence.')
print('Foreign Key- It is a column (or columns) that references a column (most often the primary key) of another table.')

#Q6-Write a python code to connect MySQL to python. Explain the cursor() and execute() method.
print('\nPython code to connect MySQL to python-')
print('''import mysql.connector
mydb=mysql.connector.connect(
     host="localhost",
     user="abc",
     password="password")
mycursor=mydb.cursor()''')

print('\ncursor()-It is an object that is used to make the connection for executing SQL queries.')
print('execute()-It is used to execute all the SQL queries.')

#Q7-Give the order of execution of SQL clauses in an SQL query.

print('''\nThe order of execution of SQL clauses in an SQL query-
-->FROM, including JOINs
-->WHERE
-->GROUP BY
-->HAVING
-->WINDOW functions
-->SELECT
-->DISTINCT
-->UNION
-->ORDER BY
-->LIMIT and OFFSET''')